// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package storage

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	bpmn "nayra/internal/bpmn"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c9d2b01DecodeNayraInternalStorage(in *jlexer.Lexer, out *tRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.ID).UnmarshalText(data))
			}
		case "definitionsId":
			if in.IsNull() {
				in.Skip()
				out.Definitions = nil
			} else {
				if out.Definitions == nil {
					out.Definitions = new(bpmn.Definitions)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.Definitions).UnmarshalJSON(data))
				}
			}
		case "instances":
			if in.IsNull() {
				in.Skip()
				out.Instances = nil
			} else {
				in.Delim('[')
				if out.Instances == nil {
					if !in.IsDelim(']') {
						out.Instances = make([]*bpmn.Instance, 0, 8)
					} else {
						out.Instances = []*bpmn.Instance{}
					}
				} else {
					out.Instances = (out.Instances)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *bpmn.Instance
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(bpmn.Instance)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Instances = append(out.Instances, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c9d2b01EncodeNayraInternalStorage(out *jwriter.Writer, in tRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"definitionsId\":"
		out.RawString(prefix)
		if in.Definitions == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.Definitions).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"instances\":"
		out.RawString(prefix)
		if in.Instances == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Instances {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v tRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c9d2b01EncodeNayraInternalStorage(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v tRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c9d2b01EncodeNayraInternalStorage(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *tRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c9d2b01DecodeNayraInternalStorage(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *tRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c9d2b01DecodeNayraInternalStorage(l, v)
}
